### ISSUE TITLE
Temperature Tower Not Manifold

### ISSUE THREAD

**Issue by jbeardon** [SoftFever/BambuStudio-SoftFever#343]
**Describe the bug**
Slicer reports that the temperature_tower.stl  has 18 non-manifold edges

It prints OK but hardly ideal!

![image](https://user-images.githubusercontent.com/14904316/220589735-77c01bbd-1c05-46a5-98c1-9cefc1364aea.png)

**Comment by SoftFever** [comment]
It's a bit tricky as the non-manifold edges are created when splitting the model.
This doesn't cause any issue though.

**Comment by jbeardon** [comment]
Ah, fair enough. Could the test not be produced using scripted height modifiers, removing the requirement to split the model?
Just a thought :-)

**Comment by hliebscher** [comment]
SF fixed in the last patch ... for MAC ist works THANKS

**Comment by SoftFever** [comment]
Fixed in [463393c](https://github.com/SoftFever/BambuStudio-SoftFever/commit/463393c96952d67f7dd8aa8a0d476f6e36092ba5)

We can arrange and stack each block in the code too. 
But I found an easy way out ;)

**Comment by sdylewski** [comment]
Still broken in 1.9.0 on OSX

**Comment by SoCuul** [comment]
Still broken in 2.0.0 on macOS

**Comment by EYEhaveYOU95** [comment]
There is still the same ERROR: 14 non-manifold edges.

Currently in Orca Slicer 2.2.0-beta 

I hope it still works as anticipated with using REPAIR, as repair itself works.

**Comment by shauneccles** [comment]
@SoftFever this is still an issue in 2.2.0 release - can you reopen or shall I log another issue?

**Comment by SoCuul** [comment]
> @SoftFever this is still an issue in 2.2.0 release - can you reopen or shall I log another issue?

You should probably re-open. Would bring it to the top of the issues list as well.

**Comment by 3dRikal** [comment]
Still an issue 2.2.0 Win

**Comment by GAZ082** [comment]
Issue in Linux with 2.2.3

**Comment by paulcake69** [comment]
This is still an issue

**Comment by Flyerone** [comment]
Version 2.3.1 this issue persists.

**Comment by marauderlabs** [comment]
Version 2.3.1 this issue persists. (I noticed at least on the portable one)
